package pricing

func BuiltinAnthropicProvider() StaticProvider {
	return NewStaticProvider([]ModelPrice{
		{
			Pattern:              "claude-opus-4-8*",
			StandardInputPerMTok: mustDecimal("5.00"),
			CacheWrite5mPerMTok:  mustDecimal("6.25"),
			CacheWrite1hPerMTok:  mustDecimal("10.00"),
			CacheReadPerMTok:     mustDecimal("0.50"),
			OutputPerMTok:        mustDecimal("25.00"),
		},
		{
			Pattern:              "claude-opus-4.8*",
			StandardInputPerMTok: mustDecimal("5.00"),
			CacheWrite5mPerMTok:  mustDecimal("6.25"),
			CacheWrite1hPerMTok:  mustDecimal("10.00"),
			CacheReadPerMTok:     mustDecimal("0.50"),
			OutputPerMTok:        mustDecimal("25.00"),
		},
		{
			Pattern:              "claude-opus-4-7*",
			StandardInputPerMTok: mustDecimal("5.00"),
			CacheWrite5mPerMTok:  mustDecimal("6.25"),
			CacheWrite1hPerMTok:  mustDecimal("10.00"),
			CacheReadPerMTok:     mustDecimal("0.50"),
			OutputPerMTok:        mustDecimal("25.00"),
		},
		{
			Pattern:              "claude-opus-4.7*",
			StandardInputPerMTok: mustDecimal("5.00"),
			CacheWrite5mPerMTok:  mustDecimal("6.25"),
			CacheWrite1hPerMTok:  mustDecimal("10.00"),
			CacheReadPerMTok:     mustDecimal("0.50"),
			OutputPerMTok:        mustDecimal("25.00"),
		},
		{
			Pattern:              "claude-opus-4-6*",
			StandardInputPerMTok: mustDecimal("5.00"),
			CacheWrite5mPerMTok:  mustDecimal("6.25"),
			CacheWrite1hPerMTok:  mustDecimal("10.00"),
			CacheReadPerMTok:     mustDecimal("0.50"),
			OutputPerMTok:        mustDecimal("25.00"),
		},
		{
			Pattern:              "claude-opus-4.6*",
			StandardInputPerMTok: mustDecimal("5.00"),
			CacheWrite5mPerMTok:  mustDecimal("6.25"),
			CacheWrite1hPerMTok:  mustDecimal("10.00"),
			CacheReadPerMTok:     mustDecimal("0.50"),
			OutputPerMTok:        mustDecimal("25.00"),
		},
		{
			Pattern:              "claude-opus-4-5*",
			StandardInputPerMTok: mustDecimal("5.00"),
			CacheWrite5mPerMTok:  mustDecimal("6.25"),
			CacheWrite1hPerMTok:  mustDecimal("10.00"),
			CacheReadPerMTok:     mustDecimal("0.50"),
			OutputPerMTok:        mustDecimal("25.00"),
		},
		{
			Pattern:              "claude-opus-4.5*",
			StandardInputPerMTok: mustDecimal("5.00"),
			CacheWrite5mPerMTok:  mustDecimal("6.25"),
			CacheWrite1hPerMTok:  mustDecimal("10.00"),
			CacheReadPerMTok:     mustDecimal("0.50"),
			OutputPerMTok:        mustDecimal("25.00"),
		},
		{
			Pattern:              "claude-opus-4-1*",
			StandardInputPerMTok: mustDecimal("15.00"),
			CacheWrite5mPerMTok:  mustDecimal("18.75"),
			CacheWrite1hPerMTok:  mustDecimal("30.00"),
			CacheReadPerMTok:     mustDecimal("1.50"),
			OutputPerMTok:        mustDecimal("75.00"),
		},
		{
			Pattern:              "claude-opus-4.1*",
			StandardInputPerMTok: mustDecimal("15.00"),
			CacheWrite5mPerMTok:  mustDecimal("18.75"),
			CacheWrite1hPerMTok:  mustDecimal("30.00"),
			CacheReadPerMTok:     mustDecimal("1.50"),
			OutputPerMTok:        mustDecimal("75.00"),
		},
		{
			Pattern:              "claude-opus-4*",
			StandardInputPerMTok: mustDecimal("15.00"),
			CacheWrite5mPerMTok:  mustDecimal("18.75"),
			CacheWrite1hPerMTok:  mustDecimal("30.00"),
			CacheReadPerMTok:     mustDecimal("1.50"),
			OutputPerMTok:        mustDecimal("75.00"),
		},
		{
			Pattern:              "claude-sonnet-4*",
			StandardInputPerMTok: mustDecimal("3.00"),
			CacheWrite5mPerMTok:  mustDecimal("3.75"),
			CacheWrite1hPerMTok:  mustDecimal("6.00"),
			CacheReadPerMTok:     mustDecimal("0.30"),
			OutputPerMTok:        mustDecimal("15.00"),
		},
		{
			Pattern:              "claude-haiku-4.5*",
			StandardInputPerMTok: mustDecimal("1.00"),
			CacheWrite5mPerMTok:  mustDecimal("1.25"),
			CacheWrite1hPerMTok:  mustDecimal("2.00"),
			CacheReadPerMTok:     mustDecimal("0.10"),
			OutputPerMTok:        mustDecimal("5.00"),
		},
		{
			Pattern:              "claude-haiku-4*",
			StandardInputPerMTok: mustDecimal("1.00"),
			CacheWrite5mPerMTok:  mustDecimal("1.25"),
			CacheWrite1hPerMTok:  mustDecimal("2.00"),
			CacheReadPerMTok:     mustDecimal("0.10"),
			OutputPerMTok:        mustDecimal("5.00"),
		},
		{
			Pattern:              "claude-3-5-haiku*",
			StandardInputPerMTok: mustDecimal("0.80"),
			CacheWrite5mPerMTok:  mustDecimal("1.00"),
			CacheWrite1hPerMTok:  mustDecimal("1.60"),
			CacheReadPerMTok:     mustDecimal("0.08"),
			OutputPerMTok:        mustDecimal("4.00"),
		},
		{
			Pattern:              "*",
			StandardInputPerMTok: mustDecimal("3.00"),
			CacheWrite5mPerMTok:  mustDecimal("3.75"),
			CacheWrite1hPerMTok:  mustDecimal("6.00"),
			CacheReadPerMTok:     mustDecimal("0.30"),
			OutputPerMTok:        mustDecimal("15.00"),
		},
	})
}
